version: "3.8"

services:
  mega-sena-database:
    container_name: mega-sena-database
    image: mysql:5.7
    volumes:
      - mega_sena_database
    networks:
      - mega_sena_database_net
    environment:
      - MYSQL_ROOT_PASSWORD=megasena
      - MYSQL_USER=megasena_rw
      - MYSQL_PASSWORD=megasena
      - MYSQL_DATABASE=megasena
    ports:
      - 3306:3306

networks:
  mega_sena_database_net:
    external: true

volumes:
  mega_sena_database: { }
